export const CONFIG = {
  api: 'http://localhost:3007',
  dNone: 'd-none',
  news: '.news',
  about: '.about',
  searchPage: '.search-page',
  searchPageResults: '.search-page .results',
  searchNoResult: 'Подходящих документов не найдено.',
  navSearch: '.form-inline',
  searchInput: '#search-input',
  navNewsline: '#nav-newsline',
  navAbout: '#nav-about',
  allContent: '.all-content',
  errorPage: '.error-page',
  singleNews: '.single-news',
  articleName: '.single-news .card-header',
  articleContent: '.single-news .full',
  articleContentImg: '.single-news .full .img-large',
  articleBack: '.single-news .back',
  aboutBack: '.about .back',
};
